version: '3'
services:
  storybook-web:
    build: 
      context: ../../fe/aspnetcore-react-ssr
      dockerfile: Dockerfile-storybook
    image: storybook-web:storybook
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "8091:9009"
  react-ssr-web:
    build: 
      context: ../../fe/aspnetcore-react-ssr
      dockerfile: Dockerfile-ssr
    image: react-ssr-web:react-ssr
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "3000:3000"
  aspnetcore-web:
    build: ../../be/src
    image: aspnetcore-web:aspnetcore
    restart: always
    depends_on: 
      - react-ssr-web
    ports:
      - "51111:443"
      - "51112:80"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=aspnetcore