version: '3'
services:
  storybook-web:
    build: 
      context: ../../fe
      dockerfile: Dockerfile-storybook-dev
    image: storybook-web:storybook
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "8091:9009"
  react-ssr-web:
    build: 
      context: ../../fe
      dockerfile: Dockerfile-ssr-dev
    image: react-ssr-web:react-ssr
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "3000:3000"
  aspnetcore-web:
    build: 
      context: ../../be/src
      dockerfile: Dockerfile-dev
    image: aspnetcore-web:aspnetcore
    restart: always
    depends_on: 
      - react-ssr-web
    ports:
      - "51117:80"